name: bases
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.7.2"

resolution: workspace

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

  dio: any
  bloc: any
  flutter_bloc: any
  retrofit: any

dev_dependencies:
  lints: ^5.0.0
  flutter_lints: ^5.0.0
