name: home
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

resolution: workspace

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

  get_it: any
  injectable: any

dev_dependencies:
  build_runner: any
  injectable_generator: any