name: dart_workspace

packages:
  - app/**
  - features/**
  - packages/**

scripts:
  build-runner:
    run: melos exec -- "dart run build_runner build -d"
    description: "Run build runner in all package that depends on build_runner."
    packageFilters:
      dependsOn:
        - "build_runner"

  build-runner-watch:
    run: melos exec -- "dart run build_runner watch --delete-conflicting-outputs"
    description: "Run build runner in all package that depends on build_runner."
    packageFilters:
      dependsOn:
        - "build_runner"

  # TODO: add script to build apk
  # TODO: add script to flutter pub get
