name: network
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.7.2"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  session: any

  # HTTP Request
  dio: any
  
  # Logging
  logger: ^2.0.1

dev_dependencies:
  lints: any
