name: common
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  product: any

  core: any
  bases: any

  dio: any
  json_annotation: any
  retrofit: any
  auto_route: any

  blocy: any
  flutter_bloc: any

  injectable: any

dev_dependencies:
  flutter_lints: any
  build_runner: any
  json_serializable: any
  retrofit_generator: any
  injectable_generator: any
  auto_route_generator: any