name: core
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

resolution: workspace

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  
  home: any
  network: any

  dio: any

  get_it: any
  injectable: any

dev_dependencies:
  build_runner: any
  injectable_generator: any